### ISSUE TITLE
failing unit test

### ISSUE THREAD

**Issue by someara** [zerotier/go-ztcentral#26]
Hello!

I went to go start working on this, but it's not passing unit tests out of the box

```
foxtrot:~/src/zerotier/go-ztcentral$ go test
--- FAIL: TestGetMember (1.69s)
    member_test.go:68: Status code 500: status code was not 200
--- FAIL: TestCRUDMembers (2.08s)
    member_test.go:115: Status code 500: status code was not 200
FAIL
exit status 1
FAIL	github.com/zerotier/go-ztcentral	20.793s
```

**Comment by someara** [comment]
I've tracked this down as far as I can in the someara-dev branch, and it seems to be a legit error...
@glimberg any chance you can paste some server side logs?

-s

**Comment by someara** [comment]
The someara-dev branch comments out all tests except for TestGetMember.
It was creating a public network by default, so I corrected that...
Now, it is successfully using CreateAuthorizedMember, but still returning a 500

**Comment by someara** [comment]
```
foxtrot:~/src/zerotier/go-ztcentral$ go test -v
=== RUN   TestGetMember
DEBUG: *net.Config.Id: 272f5eae16efecae
DEBUG: aliceID.IDString():c85cece7c0
    member_test.go:73: Status code 500: status code was not 200
--- FAIL: TestGetMember (1.06s)
FAIL
exit status 1
FAIL	github.com/zerotier/go-ztcentral	1.411s
foxtrot:~/src/zerotier/go-ztcentral$```

**Comment by someara** [comment]
Can this be fixed server side?

**Comment by laduke** [comment]
yeah

**Comment by laduke** [comment]
I have a fix for that null issue, but there is the api rate limit 429 issue which i'm not sure how to deal with yet
